# Generated by Django 4.2.9 on 2024-02-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
